# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-02 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('any', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=100)),
                ('log', models.ManyToManyField(to='any.ProjectLog')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
